filepath = r"D:\Using Pyrhon to Interact with the Operating System\spyder.txt"
file = open(filepath)
# Os checks if we have permission to open the file and then gives our code a
# FILE DEASCRIPTOR. This is a token generated by the OS that allows programs to do more operations with the file. In Python, this file descriptor is stored as an attribute of the files object. The file object gives us a bunch of methods that we can use to operate with the file. Now, with this file object, we can read the contents of the file and print them to the screen.
print(file.readline())
print(file.read())

file.close()

# OPEN _ USE _CLOSE pattern
# using with block, python will automatically close the file

with open(filepath) as file:
    print(file.readline())
